### ISSUE TITLE
Is there a way to set up dircolors on MacOS?

### ISSUE THREAD

**Issue by gayfalcon** [dracula/dircolors#2]
Hello!

I've been a fan of dracula theme for a long time now, but I moved from Linux to MacOS. I have a question:

Is there a way to set dircolors on MacOS? Tried looking up the internet, however, no real working solution was found. Any ideas would be great! 

I use iTerm2 btw.

Thanks in advance.

**Comment by scop** [comment]
I don't know about that setup, but the first entry in the list brought up by clicking Mac at https://draculatheme.com/ is iTerm, which includes some iTerm 2 instructions.
